import './globals.css'
import localfont from 'next/font/local';

const Avenir = localfont({src: '../fonts/avenir/Avenir-Light.ttf'})

export const metadata = {
  title: 'GOLF LEADERBOARD',
  description: 'Generated by Lucas Gutierrez',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Avenir.className}>{children}</body>
    </html>
  )
}
